# Generated by Django 5.0.3 on 2024-03-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('title', models.TextField(verbose_name='Title(s)')),
                ('available_for_freelancing', models.BooleanField(verbose_name='Available For Freelancing')),
                ('image', models.ImageField(upload_to='images/me', verbose_name='Image')),
                ('years_experience', models.IntegerField(verbose_name='Experience(year)')),
                ('satisfied_customers', models.IntegerField(verbose_name='Satisfied Customers')),
                ('resume_file', models.FileField(upload_to='files/me', verbose_name='Resume')),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
            ],
            options={
                'db_table': 'my_info',
            },
        ),
    ]
