# Generated by Django 5.0.3 on 2024-03-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfomodel',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook Url'),
        ),
        migrations.AddField(
            model_name='myinfomodel',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram Url'),
        ),
        migrations.AddField(
            model_name='myinfomodel',
            name='linked_in',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Linkedin Url'),
        ),
        migrations.AddField(
            model_name='myinfomodel',
            name='twitter',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Twitter Url'),
        ),
    ]
