# Generated by Django 5.0.3 on 2024-03-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Image Alt'),
        ),
    ]
