# Generated by Django 5.0.3 on 2024-03-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_module', '0002_myinfo_image_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myinfo',
            name='image_alt',
        ),
    ]
