# Generated by Django 5.0.3 on 2024-03-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_module', '0003_remove_myinfo_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='resume_file',
            field=models.FileField(upload_to='otherFiles/me', verbose_name='Resume'),
        ),
    ]
