# Generated by Django 5.0.3 on 2024-03-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_module', '0003_myinfomodel_address_myinfomodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfomodel',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
    ]
