# Generated by Django 5.0.3 on 2024-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_module', '0004_myinfomodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfomodel',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='About Me'),
        ),
    ]
