# Generated by Django 5.0.3 on 2024-03-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_module', '0005_myinfomodel_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfomodel',
            name='about_me_extra',
            field=models.TextField(blank=True, null=True, verbose_name='About Me More'),
        ),
    ]
