# Generated by Django 5.0.3 on 2024-03-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_module', '0005_services_alter_myinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShowCaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('short_description', models.TextField(verbose_name='Short Description')),
            ],
            options={
                'verbose_name': 'Work Show Case',
                'verbose_name_plural': 'Work Show Cases',
                'db_table': 'work_show_case',
            },
        ),
        migrations.RenameModel(
            old_name='MyInfo',
            new_name='MyInfoModel',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='ServicesModel',
        ),
    ]
