# Generated by Django 5.0.3 on 2024-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_module', '0006_myinfomodel_about_me_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfomodel',
            name='country',
            field=models.CharField(default='Iran', max_length=200, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
