# Generated by Django 5.0.3 on 2024-03-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_module', '0006_workshowcasemodel_rename_myinfo_myinfomodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='workshowcasemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/works', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='workshowcasemodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
