# Generated by Django 5.0.3 on 2024-03-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='logo',
            field=models.ImageField(null=True, upload_to='uploads/logos', verbose_name='Service Logo'),
        ),
    ]
