# Generated by Django 5.0.3 on 2024-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0002_servicesmodel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='svg_code',
            field=models.TextField(blank=True, null=True, verbose_name='Svg File Html Code'),
        ),
    ]
