# Generated by Django 5.0.3 on 2024-03-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_abilitiesmodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200, verbose_name='University')),
                ('start_year', models.IntegerField(verbose_name='Start Year')),
                ('finish_year', models.IntegerField(verbose_name='Finish Year')),
                ('degree', models.IntegerField(choices=[(1, 'High School'), (2, 'Bachelor'), (3, 'Master')])),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('is_active', models.BooleanField(verbose_name='is Active')),
            ],
        ),
    ]
