# Generated by Django 5.0.3 on 2024-03-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_educationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='finish_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Finish Year'),
        ),
    ]
