# Generated by Django 5.0.3 on 2024-03-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_alter_educationmodel_finish_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationmodel',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelTable(
            name='educationmodel',
            table='Education',
        ),
    ]
