# Generated by Django 5.0.3 on 2024-03-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('message', models.TextField(verbose_name='Your Message')),
            ],
            options={
                'verbose_name': 'Consult',
                'verbose_name_plural': 'Consults',
                'db_table': 'consults',
            },
        ),
    ]
