# Generated by Django 5.0.3 on 2024-03-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshowcasemodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Creation Date'),
        ),
    ]
