# Generated by Django 5.0.3 on 2024-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_module', '0002_workshowcasemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshowcasemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug'),
        ),
    ]
