# Generated by Django 5.0.3 on 2024-03-26 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_module', '0004_alter_workshowcasemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshowcasemodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Explain More About Project'),
        ),
        migrations.AddField(
            model_name='workshowcasemodel',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Project Url'),
        ),
        migrations.CreateModel(
            name='WorkShowCaseCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.ImageField(upload_to='images/work/galleries', verbose_name='Detail Image')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase_module.workshowcasemodel', verbose_name='work')),
            ],
            options={
                'verbose_name': 'Work Show Category',
                'verbose_name_plural': 'Work Show Categories',
                'db_table': 'work_show_case_category',
            },
        ),
        migrations.CreateModel(
            name='WorkShowCaseGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/work/galleries', verbose_name='Detail Image')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase_module.workshowcasemodel', verbose_name='work')),
            ],
            options={
                'verbose_name': 'Work Show Image',
                'verbose_name_plural': 'Work Show Gallery',
                'db_table': 'work_show_case_gallery',
            },
        ),
    ]
