# Generated by Django 5.0.3 on 2024-03-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_module', '0005_workshowcasemodel_description_workshowcasemodel_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkShowCaseCategoryModel',
        ),
    ]
