# Generated by Django 5.0.3 on 2024-03-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_module', '0006_delete_workshowcasecategorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkShowCaseGalleryModel',
        ),
    ]
