# Generated by Django 5.0.3 on 2024-03-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_module', '0007_delete_workshowcasegallerymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Category Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Work Category',
                'verbose_name_plural': 'Work Categories',
                'db_table': 'work_category',
            },
        ),
        migrations.AddField(
            model_name='workshowcasemodel',
            name='main_technology',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Project Main Technology'),
        ),
        migrations.AddField(
            model_name='workshowcasemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase_module.workcategory', verbose_name='Category'),
        ),
    ]
