# Generated by Django 5.0.3 on 2024-03-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date of Article')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/articles', verbose_name='Image')),
                ('is_active', models.BooleanField(verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'article',
            },
        ),
    ]
