# Generated by Django 5.0.3 on 2024-03-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('work_place', models.CharField(max_length=200, verbose_name='Company')),
                ('start_year', models.IntegerField(verbose_name='Start Year')),
                ('finish_year', models.IntegerField(blank=True, null=True, verbose_name='Finish Year')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'db_table': 'work_experience',
            },
        ),
    ]
